export const yoyoBrands = [
	'3yo3',
	'44CLASH',
	'44RPM',
	'A-RT',
	'Ace Yo',
	'Adegle',
	'Aero-Yo',
	'AHAY - A House About Yo-Yo',
	'Anti-Yo',
	'Atmos Projects',
	'Aufheben',
	'Aufheben x Unparalleled',
	'Auldey',
	'Auldey x Turning Point',
	'Axis Yoyos',
	'B.W.W',
	'Bandai',
	'Bandai Hyper Yo-Yo',
	'Basecamp',
	'Bist',
	'Blood Brothers',
	'Break Beat Yo',
	'C3yoyodesign',
	'C3yoyodesign × CLYW',
	'C3yoyodesign x Hspin',
	'C3yoyodesign x Magic YoYo',
	'C3yoyodesign x Porykon',
	'C3yoyodesign x W1LD',
	'C3yoyodesign x YoYoJam',
	'Came-Yo',
	'Candy Dice',
	'Canopy Collection',
	'Caribou Lodge',
	'Caribou Lodge x Luftverk',
	'Caribou Lodge x SUS YOYOMECHANICS',
	'Centerpiece Throws',
	'Cerevo',
	'Cheatcode',
	'Chico Yo-Yo Company',
	'Cold Metal',
	'Core Concept Yoyos',
	'Core Concept Yoyos x SF Yoyos',
	'Crucial',
	'Dale Tubat',
	'Dif-e-Yo',
	'DreamYo',
	'Dressel Designs Yoyos',
	'Duncan',
	'Efreet',
	'Elemental',
	'empathy',
	'en',
	'Enso Yoyos',
	'Eternal Throw',
	'FPM + Unparalleled',
	'Free Wing YoYo Studio',
	'Freshthings',
	'G Squared',
	'G Squared Yoyos',
	'G2',
	'G2 Yoyos',
	'General-Yo',
	'God-Tricks',
	'Hany',
	'heArts',
	'Henrys',
	'Hiroshima Toyo Carp',
	'Hobonichi',
	'Hspin',
	'Hubless Yoyo',
	'Hydrangea',
	'ILOVEYOYO',
	'ILYY',
	'Innovative YoYo Concepts',
	'iYoYo',
	'iYoYo x YoYoFactory',
	'Japan Looping Solutions',
	'Japan Technology',
	'Japanese Vendor',
	'Jazz-Yo',
	'K-Project',
	'KenTech',
	'King Yo Star',
	'Laid Back Swing',
	'Luftverk',
	'MadHouse',
	'Magicyoyo',
	'Markmont.',
	'Matsui Gaming Machine',
	'MIYO yoyo studio',
	'MonkeyfingeR',
	'Motion Yoyos',
	'Non Brand',
	'Northern Spin Co.',
	'Offset Yoyo',
	'Old School Throw',
	'onedrop',
	'onedrop x CLYW',
	'onedrop x ILOVEYOYO',
	'onedrop x Toxic String',
	'Oxygene',
	'Polyform',
	'Pool Party YoYos',
	'Rain City Skills',
	'Recess',
	'RecRev',
	'REWIND',
	'Rewind',
	'REWIND x SUS YOYO MECHANICS',
	'Reykjavik Return Tops',
	'RiHara',
	'Rosyo',
	'Round Spinning Objects',
	'Sengoku',
	'Sense YoYo',
	'SF Yoyos',
	'SF Yoyos x A-RT',
	'Shinwoo',
	'Shuriken Yoyos',
	'Singwon Yoyo',
	'SLUSNY',
	'Smashing YoYo Company',
	'Sōchí Company',
	'sOMEThING',
	'sOMEThING x Japan Technology',
	'sOMEThING x UNPRLD',
	'SOMETHINGIZM',
	'sOMRThING x Japan Technology',
	'Sphere',
	'Spin Dynamics',
	'Spintek',
	'SPYY',
	'Stardust',
	'Static Unresponsives Company',
	'String Theory Yoyos',
	'Sturm Panzer',
	'SUS YOYO MECHANICS',
	'Takuto.Desighn',
	'Thesis Yoyos',
	'Throw Revolution',
	'Tom Kuhn',
	'Tom Kuhn x Chico Yo-Yo Company',
	'TOMY Company',
	'Top Yo',
	'Top Yo x Even',
	'Top Yo x July YoYo',
	'Turning Center',
	'Turning Point',
	'Turning Point x YoYoFactory',
	'UNPRLD',
	'UNPRLD x Top Yo',
	'Vosun',
	'VS Newton',
	'Vulto',
	'W1LD',
	'Werrd',
	'XCube',
	'Yi Chenghao',
	'YJ YOYO',
	'YO-YO STORE REWIND WORLDWIDE',
	'Yoku YoYo Design',
	'Yomega',
	'Yomega x onedrop',
	'Yomega x YoYoJam',
	'Yonity',
	'YoYo Empire',
	'YOYO Laboratory',
	'YoYo Palace',
	'YoYo Planet',
	'YOYO STORE REWIND WORLDWIDE',
	'YOYO-Y',
	'YoYoFactory',
	'YOYOFFICER',
	'YOYOFFICER x Auldy',
	'Yoyofriends',
	'YoYoJam',
	'YoYoJoker',
	'YoYoJoker x YANEURA WORKS',
	'YOYOMAKER',
	'Yoyomonster',
	'Yoyorecreation',
	'YOYOSKEEL',
	'Zero Gravity Return Tops',
];
