import { Roboto, Open_Sans } from 'next/font/google';
import '@/styles/globals.css';
import Header from './components/header/header';

const roboto = Roboto({
	variable: '--font-roboto',
	subsets: ['latin'],
});

const openSans = Open_Sans({
	variable: '--font-open-sans',
	subsets: ['latin'],
});

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<body className={`${roboto.variable} ${openSans.variable}`}>
				<Header />
				{children}
			</body>
		</html>
	);
}
